services:
  java17:
    image: ghcr.io/noeppi-noeppi/images:java17
    build:
      context: java
      args:
        JDK_URL: https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.10%2B7/OpenJDK17U-jdk_x64_linux_hotspot_17.0.10_7.tar.gz
        
  java21:
    image: ghcr.io/noeppi-noeppi/images:java21
    build:
      context: java
      args:
        JDK_URL: https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.2%2B13/OpenJDK21U-jdk_x64_linux_hotspot_21.0.2_13.tar.gz
